config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  root to: 'pages#home'

  get "dashboard", to: "users#dashboard"

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to dashboard_path, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @disable_nav = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @meetings = Meeting.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def say_my_name(user)
    puts "#{user.name}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' unless @disable_nav%>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :start_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/pages/home.html.erb
<%= render "shared/navbar_home"%>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'home.jpg'%>);">
  <div class="banner-content">
    <h1>Development Center</h1>
    <p>Welcome on Jouve & Associés assessments platform</p>
    <% if user_signed_in? %>
      <%= link_to "My dashboard", dashboard_path,class:"btn btn-danger btn-lg"%>
    <%end%>
  </div>
</div>

app/views/shared/_code_pen_calendar.html.erb
<div class="calendar">

  <div class="col leftCol">
    <div class="content">
      <h1 class="date">Friday<span>September 12th</span></h1>
      <div class="notes">
        <p>
          <input type="text" value="" placeholder="new note"/>
          <a href="#" title="Add note" class="addNote animate">+</a>
        </p>
        <ul class="noteList">
          <li>Headbutt a lion<a href="#" title="Remove note" class="removeNote animate">x</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col rightCol">
    <div class="content">
      <h2 class="year">2013</h2>
      <ul class="months">
        <li><a href="#" title="Jan" data-value="1">Jan</a></li>
        <li><a href="#" title="Feb" data-value="2">Feb</a></li>
        <li><a href="#" title="Mar" data-value="3">Mar</a></li>
        <li><a href="#" title="Apr" data-value="4">Apr</a></li>
        <li><a href="#" title="May" data-value="5">May</a></li>
        <li><a href="#" title="Jun" data-value="6">Jun</a></li>
        <li><a href="#" title="Jul" data-value="7">Jul</a></li>
        <li><a href="#" title="Aug" data-value="8">Aug</a></li>
        <li><a href="#" title="Sep" data-value="9" class="selected">Sep</a></li>
        <li><a href="#" title="Oct" data-value="10">Oct</a></li>
        <li><a href="#" title="Nov" data-value="11">Nov</a></li>
        <li><a href="#" title="Dec" data-value="12">Dec</a></li>
      </ul>
      <div class="clearfix"></div>
      <ul class="weekday">
        <li><a href="#" title="Mon" data-value="1">Mon</a></li>
        <li><a href="#" title="Tue" data-value="2">Tue</a></li>
        <li><a href="#" title="Wed" data-value="3">Wed</a></li>
        <li><a href="#" title="Thu" data-value="4">Thu</a></li>
        <li><a href="#" title="Fri" data-value="5">Fri</a></li>
        <li><a href="#" title="Say" data-value="6">Sat</a></li>
        <li><a href="#" title="Sun" data-value="7">Sun</a></li>
      </ul>
      <div class="clearfix"></div>
      <ul class="days">
        <script>
          for( var _i = 1; _i <= 31; _i += 1 ){
            var _addClass = '';
            if( _i === 12 ){ _addClass = ' class="selected"'; }

            switch( _i ){
              case 8:
              case 10:
              case 27:
                _addClass = ' class="event"';
              break;
            }

            document.write( '<li><a href="#" title="'+_i+'" data-value="'+_i+'"'+_addClass+'>'+_i+'</a></li>' );
          }
        </script>
      </ul>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="clearfix"></div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-else">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-jouve.png"%>
    <%= image_tag "logo-orange.png" %>

  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://www.fao.org/fileadmin/templates/aiq2013/images/user-placeholder.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

     <!-- Login text link -->
      <%= link_to t("sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link-else" %>

      <!-- Button (call-to-action) -->
      <%= link_to t("sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link-else" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar-wagon navbar-wagon-fixed navbar-wagon-home">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-jouve.png" %>
    <%= image_tag "logo-orange.png" %>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://www.fao.org/fileadmin/templates/aiq2013/images/user-placeholder.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

     <!-- Login text link -->
      <%= link_to t("sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link-home" %>

      <!-- Button (call-to-action) -->
      <%= link_to t("sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link-home" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %> -  Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_user_corner.html.erb
<div class="user-corner-content">
  <div>
    <h3 class="text-center">My infos</h3>
    <p>
      <div class="coach">
        <div class="team-avatar">
          <%= image_tag "http://www.fao.org/fileadmin/templates/aiq2013/images/user-placeholder.jpg", class:"avatar-large"%>
        </div>
        <div class="team-infos">
            <div class="name">Jean DUPONT</div>
            <div class="position">Coach</div>

        </div>
      </div>
    </p>

    <p>
      <div class="hunter">
        <div class="team-avatar">
          <%= image_tag "http://www.fao.org/fileadmin/templates/aiq2013/images/user-placeholder.jpg", class:"avatar-large"%>
        </div>
        <div class="team-infos">
            <div class="name">Michel MARTIN</div>
            <div class="position">Hunter</div>

        </div>
      </div>
    </p>
  </div>

  <div>
    <h3 class="text-center">My tests</h3>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="wrapper-gray">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-right">
        <%= link_to "Add a new meeting", new_meeting_path ,class:"btn btn-danger"%>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
          <h2 class="text-center">My corner</h2>
        <div class="card" id="user-corner">
          <%= render "users/user_corner"%>
        </div>
      </div>
      <div class="col-sm-8">
          <h2 class="text-center">Calendar</h2>
        <div class="card" id="calendar">
          <%= week_calendar number_of_weeks: 2, events: @meetings do |date, meetings| %>
            <div class="date-square">
              <a href="#" class="date-link" data-toggle="modal" data-target="#modal_<%=date.jd%>">
              </a>

                <div class="number text-center">
                  <div class="special">
                    <%= date.day%>
                  </div>
                </div>
                <% meetings.each do |meeting| %>
                  <!-- <div class="meeting" style="color:green;">
                    <%= meeting.name %>
                  </div> -->
                <% end %>
            </div>

            <!-- Encart meeting -->

            <!-- Modal -->
            <div class="modal fade" id="modal_<%=date.jd%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"><%= date%></h4>
                  </div>
                  <div class="modal-body">
                    <% if meetings.select { |meeting| meeting.start_time.to_date == date}.any?%>
                      <% meetings.select { |meeting| meeting.start_time.to_date == date}.each do |meeting| %>
                        <%= meeting.name %>
                      <%end%>
                    <%else%>
                     <p>Nothing planned this day</p>
                    <%end%>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>


          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- <div class="codepen">
  <div class="row">
    <%= render "shared/code_pen_calendar"%>

  </div>
</div> -->
<% content_for(:after_js) do %>
<script>
  $(document).ready(function(){
    // Gestion d'aujourd'hui
    $(".today .number .special").addClass("badge badge-red");

    // Gestion du hover sur date
    $( ".date-square" ).hover(function() {
        $(this).find('.special').addClass('hovered');
      }, function () {
        // if ($("#user-corner").css('display')=='none') {
        //   // tester presence user corner
        //   $(".card-trip").removeClass("fadded");
        // }
        $(this).find('.special').removeClass('hovered');
      }
    );

    // Gestion du select
    $( ".date-square" ).click(function() {
      $('.special').removeClass('selected');
      $(this).find('.special').addClass('selected');
    });
  });
</script>
<%end%>